### ISSUE TITLE
[error] Unable To Proccess Your Request

### ISSUE THREAD

**Issue by febritecno** [abydahana/dwitri#2]
setelah instalasi normal kok error kayak gini mas. 
![screen shot 2017-04-15 at 11 06 33 pm](https://cloud.githubusercontent.com/assets/9696688/25065015/06088c92-2231-11e7-865a-b0905bc8788d.png)

**Comment by abydahana** [comment]
Saya belum mencoba mengakses melalui Safari. Bisa tolong masuk ke developer console (debugger) lalu kemudian klik kembali link dan screenshot error debugnya?

**Comment by abydahana** [comment]
Atau coba gunakan browser lain, jika tidak terjadi masalah agar supaya saya perbaiki compatibility pada Safari.

**Comment by febritecno** [comment]
mungkin ada yang salah di htaccess ya om ?
![screen shot 2017-04-15 at 11 21 08 pm](https://cloud.githubusercontent.com/assets/9696688/25065074/4260fb2e-2232-11e7-95f6-8baedae1ebd8.png)

**Comment by abydahana** [comment]
Pada saat mulai instalasi, apakah module mod_rewrite berstatus enabled atau terload? Kriteria servernya? Saya coba menggunakan Safari tidak terjadi masalah. Status 404 karena kemungkinan besar mod_rewrite belum enabled.

**Comment by abydahana** [comment]
Ternyata file .htaccess tidak terupload. Sudah saya sertakan file .htaccess, silakan download dan copy ke root folder instalasi dwitri.
